version: '3'
services:

  #PHP Service
  bot_app:
    build:
      context: ../../
      dockerfile: src/backend/Dockerfile
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ../../../:/apps/leash
      - ../../../docker/src/backend/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - app-network

  bot_rabbitmq:
      image: rabbitmq:management
      ports:
        - '9614:15672'
      networks:
        - app-network

#  chatbot-vk:
#    build:
#      context: ../../
#      dockerfile: src/backend/Dockerfile
#    image: sphp
#    tty: true
#    environment:
#      SERVICE_NAME: app
#      SERVICE_TAGS: dev
#    volumes:
#      - ../../../:/apps/leash
#      - ../../../docker/src/backend/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#    command: php artisan consumer:vk_waitForUserMessage
#    networks:
#      - app-network
    

  #Nginx Service
#  webserver:
#    image: nginx:alpine
#    container_name: webserver
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./:/var/www
#      - ./nginx/conf.d/:/etc/nginx/conf.d/
#    networks:
#      - app-network

  bot_db:
    image: postgres:12.2
    ports:
      - '18002:5432'
    environment:
      POSTGRES_DB: denis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    volumes:
      - /var/lib/docker-data/leash/postgresql:/var/lib/postgresql/data
    networks:
      - app-network
  bot_pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: php@mail.ru
      PGADMIN_DEFAULT_PASSWORD: leash
    ports:
      - '18003:80'
    image: dpage/pgadmin4
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
